site_name: iGEM Straubing
site_url: https://mydomain.org/mysite
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
  custom_dir: docs/overrides
  palette:
    primary: cyan
  logo: img/white_font_igem.png
  favicon: img/favicon.ico
nav:
  - Home: index.md
  - About us: about.md
  - Partnerships: sponsoring.md
  - Contact: Contact.md

plugins:
  - privacy

extra:
  social:
    - icon: fontawesome/brands/instagram 
      link: https://www.instagram.com/igem.straubing/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/igem-tum-campus-straubing/
    - icon: fontawesome/brands/linktree
      link: https://linktr.ee/igem_straubing
    - icon: simple/mailboxdotorg
      link: mailto:info@igem-straubing.de
  consent:
    title: Cookie consent
    description: >- 
      We may use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
extra_css:
  - styles/extra.css

copyright: Copyright Â© 2025 iGEM Straubing. All rights reserved. <a href="#__consent">Change cookie settings</a>

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.blocks.caption
